### ISSUE TITLE
readthedocs.org API reference is broken

### ISSUE THREAD

**Issue by matze** [tomography/xdesign#31]
FYI: The modules/functions seem to be [empty](https://xdesign.readthedocs.io/en/latest/api/xdesign.acquisition.html) even though they are in fact documented properly. Besides that, a gentle introduction or tutorial would be nice.

**Comment by dgursoy** [comment]
I guess some dependencies that rely on C need to be mocked on the doc config.

**Comment by carterbox** [comment]
@matze, if you look into the demos folder, there are some Jupyter notebooks that are pretty well described.  As for official introductions, I'll put that on a list.

**Comment by decarlof** [comment]
@carterbox if you like I can add the  Jupyter notebooks in the docs similar to what we did in [tomopy](http://tomopy.readthedocs.io/en/latest/demo.html)

**Comment by dgursoy** [comment]
I'd open Jupiter notebook addition in a separate thread. 

Also the API seems still failing - need to check if all C dependent packages are properly mocked.

**Comment by decarlof** [comment]
API should work fine after you accept #34 (see [my doc built)](http://myxdesign.readthedocs.io/en/latest/).
