### ISSUE TITLE
module installation issue

### ISSUE THREAD

**Issue by decarlof** [tomography/xdesign#35]
it seems python setup.py install is not working. 

There are some classes that don't make it in the installation directory. For example Soil is installed correctly but DogaCircles is not (only works when I call it from the local built directory).

```python
bash$ git clone https://github.com/decarlof/xdesign.git
bash$ cd xdesign
bash$ python setup.py install
bash$ ipython 
In [1]: from xdesign.material import Soil
In [2]: from xdesign.material import DogaCircles
quit
bash$ cd ..
bash$ ipython 
In [1]: from xdesign.material import Soil
In [2]: from xdesign.material import DogaCircles
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-8e1ceb6dfe32> in <module>()
----> 1 from xdesign.material import DogaCircles
ImportError: cannot import name DogaCircles
```

what is going on?

**Comment by carterbox** [comment]
Maybe the python path of ipython isn't the same as the install directory of setup.py?

**Comment by carterbox** [comment]
@decarlof, can you confirm that this is still an issue in `v0.2.3`? I haven't been able to recreate this bug.
