### ISSUE TITLE
translation bug

### ISSUE THREAD

**Issue by dgursoy** [tomography/xdesign#38]
When you try to translate a phantom it accepts two scalars for horizontal and vertical shifts; but actually it waits for a single vector. Unless corrected, it complains:

```TypeError: translate() takes 2 positional arguments but 3 were given```

Also there is a typo in line 514 in geometry.py: 

```if not isinstance(vector, (Point, list, nd.array))```

I believe it should be:

```if not isinstance(vector, (Point, list, np.array))```

**Comment by carterbox** [comment]
It appears that when I reorganized the geometry module to add support for more than 2 dimensions, I forgot to change the input parameters for `Phantom` and `Feature`.

**Comment by carterbox** [comment]
I pushed some fixes to [v0.2.5](xdesign@2789ba1). Let me know if it works.
