### ISSUE TITLE
xdesign installation instructions

### ISSUE THREAD

**Issue by decarlof** [tomography/xdesign#59]
I received a request from users to improve the installation process.  Is there any plan to add xdesign to conda forge?

**Comment by carterbox** [comment]
Was there any specific feedback?

There are no plans at this time. Mainly this is because not all of the dependencies are on conda. (That's probably why the installation process is annoying?) Also, I didn't think anyone beside me wanted to use this package.

**Comment by carterbox** [comment]
Actually, `xdesign` is very easy to install. If you remove `python` from the `requirements.txt`, then all the dependencies can be installed using `pip`

```bash
$ pip install -r requirements.txt
```
