### ISSUE TITLE
for the function fsim  the 'phase.phasecongmono' I do not know which package called 'phase '

### ISSUE THREAD

**Issue by acse-wz19** [tomography/xdesign#75]
I can not found import phase or other action

**Comment by carterbox** [comment]
The `fsim` metric, which was removed in `xdesign` version 0.5.4, requires the `phasepack` python package. Please see this commit for more details: https://github.com/tomography/xdesign/commit/cfbf249bb051ccae9cdd2379261cd2a74145f583

**Comment by acse-wz19** [comment]
Thanks very much.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Daniel Ching <notifications@github.com>
发送时间: Thursday, August 6, 2020 5:09:59 AM
收件人: tomography/xdesign <xdesign@noreply.github.com>
抄送: Zhang, Weilin <weilin.zhang19@imperial.ac.uk>; Author <author@noreply.github.com>
主题: Re: [tomography/xdesign] for the function fsim the 'phase.phasecongmono' I do not know which package called 'phase ' (#75)


This email from notifications@github.com originates from outside Imperial. Do not click on links and attachments unless you recognise the sender. If you trust the sender, add them to your safe senders list<https://spam.ic.ac.uk/SpamConsole/Senders.aspx> to disable email stamping for this address.



The fsim metric, which was removed in xdesign version 0.5.4, requires the phasepack python package. Please see this commit for more details: cfbf249<https://github.com/tomography/xdesign/commit/cfbf249bb051ccae9cdd2379261cd2a74145f583>

―
