### ISSUE TITLE
Pip installation

### ISSUE THREAD

**Issue by smajee** [tomography/xdesign#76]
Is there a plan to have a pip-installable release for this package?
The readme specifies only the conda installation.

**Comment by carterbox** [comment]
Hi Soumenu, Xdesign is a pure-python package, so installing from source should be trivial. You can download the source files and install using `pip install .` from the source directory.

**Comment by smajee** [comment]
Thanks.
My intention was to ask whether there is a plan to upload this to PyPi so that users can do `pip install xdesign` to install it.

The reason I asked is that I wanted to add xdesign as a dependency in another repository in a `requirements.txt` file so that a user can install the dependencies via `pip install -r requirements.txt`.
In the absence of a PyPi version, I will probably add a conda `environment.yml` file or use the github link in the `requirements.txt` file

**Comment by carterbox** [comment]
Understood! I don't have any plans to upload to PyPi. I've actually never done that before, so I don't know how to start.

**Comment by dgursoy** [comment]
I've just uploaded it to PyPI. You should be able to get it through ```pip install design``` now.

**Comment by smajee** [comment]
Thank you so much Doga!
